version: 2.1
jobs:
  build:    
    #working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m      
    steps:
      - checkout
      - restore_cache:
          key: circleci-repo-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-repo-{{ checksum "pom.xml" }}
          
      
      
      - run: 
            name: tests
            command: mvn test -DsuiteXmlFile="src/test/resources/testrunner/testng.xml"
      
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
            
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/
